version: '2'

services:
  server: 
    build: ./
    restart: unless-stopped
    command: python server.py
    ports: 
      - '8081:8081'
    volumes:
      - '.:/app'
    links:
      - elasticsearch
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    ports:
      - '9200:9200'
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
    driver: local